spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: *****
      url: jdbc:mysql://*****:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8
    jpa:
      show-sql: true
      open-in-view: true
    mail:
      host: smtp.163.com
      username: ******
      password: ******
      properties:
        mail:
          stmp:
            auth: true
            starttls:
            enable: true
            required: true
    #返回数据去除为null的
    jackson:
      default-property-inclusion: non_null
    redis:
      host: ***
      port: 6379
      password: ***
server:
  servlet:
    context-path: /wxorder
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:/code/log/
#  file: D:/code/file/fileOne.log
#  level:
#    com.txhl.wxorder.LoggerTest: debug

wechat:
  mpAppId: ***
  mpAppSecret: ***
  openAppId: ***
  openAppSecret: ***
  mchId: ***
  mchKey: ***
  keyPath: /usr/local/txhz/key/apiclient_cert.p12
  notifyUrl: ***/notify
  templateId:
    orderStatus: dZw_qNoOuIaPGkzDkWh_28BasxoA0jjf-2BFo3k-eGA

projecturl:
  wxMPAuthorize: ***.com
  wxOPenAuthorize: ***.com
  wxorder: ***.com

logging:
  level:
    com.txhl.wxorder.entity.mapper: trace